DROP TABLE IF EXISTS `reservation`;
DROP TABLE IF EXISTS `schedule`;
DROP TABLE IF EXISTS `theme`;
DROP TABLE IF EXISTS `user`;
DROP TABLE IF EXISTS `store`;

CREATE TABLE IF NOT EXISTS `store` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `store_number` VARCHAR(50) NOT NULL,
    `name` VARCHAR(255) NOT NULL,
    CONSTRAINT `PK_STORE` PRIMARY KEY (`id`),
    CONSTRAINT `UK_STORE_NUMBER` UNIQUE (`store_number`)
    );

CREATE TABLE IF NOT EXISTS `theme` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `store_id` BIGINT NULL,
    `name` VARCHAR(255) NOT NULL,
    `description` VARCHAR(255) NULL,
    `image_url` VARCHAR(255) NULL,
    `required_time` TIME NOT NULL,
    CONSTRAINT `PK_THEME` PRIMARY KEY (`id`),
    CONSTRAINT `FK_THEME_STORE` FOREIGN KEY (`store_id`) REFERENCES `store` (`id`)
);

CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `username` VARCHAR(255) NOT NULL,
    `password` VARCHAR(255) NOT NULL,
    `nickname` VARCHAR(255) NOT NULL,
    `role` VARCHAR(30) NOT NULL,
    `store_id` BIGINT NULL,
    CONSTRAINT `PK_USER` PRIMARY KEY (`id`),
    CONSTRAINT `UK_USER_NAME` UNIQUE (`username`),
    CONSTRAINT `FK_USER_STORE` FOREIGN KEY (`store_id`) REFERENCES `store` (`id`)
);

CREATE TABLE IF NOT EXISTS `schedule` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `theme_id` BIGINT NOT NULL,
    `start_at` DATETIME NOT NULL,
    `end_at` DATETIME NOT NULL,
    CONSTRAINT `PK_SCHEDULE` PRIMARY KEY (`id`),
    CONSTRAINT `FK_SCHEDULE_THEME` FOREIGN KEY (`theme_id`) REFERENCES `theme` (`id`)
);

CREATE TABLE IF NOT EXISTS `reservation` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `user_id` BIGINT NOT NULL,
    `schedule_id` BIGINT NOT NULL,
    CONSTRAINT `PK_RESERVATION` PRIMARY KEY (`id`),
    CONSTRAINT `UK_RESERVATION_SCHEDULE` UNIQUE (`schedule_id`),
    CONSTRAINT `FK_RESERVATION_USER` FOREIGN KEY (`user_id`) REFERENCES `user` (`id`),
    CONSTRAINT `FK_RESERVATION_SCHEDULE` FOREIGN KEY (`schedule_id`) REFERENCES `schedule` (`id`)
);
